require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# DSL & test convenience exceptions

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - require
    - require_relative
    - puts
    - raise
    - rescue_from
    - render
    - head
    - redirect_to
    - send_data
    - mail
    - desc
    - info
    - warn
    - error
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - '**/*.jbuilder'
    - 'Gemfile'
    - 'config.ru'

Style/RescueModifier:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  ExcludedMethods:
    - 'feature'
    - 'describe'
    - 'context'
    - 'scenario'
    - 'draw'
    - 'configure'
    - 'namespace'
    - 'shared_examples'
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'

# Customized cops

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

RSpec/NestedGroups:
  Max: 5

Capybara/FeatureMethods:
  EnabledMethods:
    - 'feature'
    - 'scenario'

# Disabled cops

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
